Blog-App: Validation feature
tajulafreen/Blog-app pull request #3
Opened 2023-09-29 18:10 UTC by tajulafreen

**In this PR I made the following changes:**

- Add the following validations:
  - For the User model:
  - Name must not be blank.
- PostsCounter must be an integer greater than or equal to zero.
- For the Post model:
  The title must not be blank.
  The title must not exceed 250 characters.
- CommentsCounter must be an integer greater than or equal to zero.
- LikesCounter must be an integer greater than or equal to zero.
- Add unit specs for all of your models' methods and validations.

2023-09-29 18:47 UTC, mckent05 requested changes
Hi @tajulafreen, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- Good job adding validation and testing your model 👏 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-29 18:47 UTC, mckent05 commented on app/models/post.rb
> +
- You have done well so far, please validate that in your post model, the LikesCounter must be an integer greater than or equal to zero. Please fix this 😄

2023-09-29 18:47 UTC, mckent05 commented on spec/models/post_spec.rb
> +end
- You have done well so far, but according to the project requirements, Any custom methods in the models should have a corresponding unit test. Please test for the `recent_comments` method in your post model 👍 👍

2023-09-29 18:47 UTC, mckent05 commented on spec/models/user_spec.rb
> +  end
- You have done well so far, but according to the project requirements, Any custom methods in the models should have a corresponding unit test. Please test for the `recent_posts` method in your user model 👍 👍. Please fix this 😄

2023-09-30 05:05 UTC, Munsa1 requested changes
Hi @tajulafreen, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
Added Tests As Requested :heavy_check_mark: 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-30 05:05 UTC, Munsa1 commented on spec/models/post_spec.rb
> +    expect(recent_comments).to eq([newer_comment5, newer_comment4, newer_comment3, newer_comment2, newer_comment1])
- [ ] Good job implementing the recent comments and recent posts tests, however your tests are not passing, kindly fix this
![image](https://github.com/tajulafreen/Blog-app/assets/81932478/034188cd-2dd4-4969-963e-08bba5193955)

2023-09-30 13:48 UTC, t-yanick approved these changes
# STATUS: MILESTONE APPROVED :1st_place_medal: 

Hi @tajulafreen , 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Requested change implemented 👍 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-30 14:56 UTC, merged