Blog-app: Integration spec
tajulafreen/Blog-app pull request #8
Opened 2023-10-10 22:07 UTC by tajulafreen

**In this PR I did the following:**
- Before fixing the N+1 issue - On the Post index page
![Screenshot (88)](https://github.com/tajulafreen/Blog-app/assets/119053190/7796bb9d-9945-4263-822e-b92dc232425b)
- Before fixing the N+1 issue - In the Post show page
![Screenshot (89)](https://github.com/tajulafreen/Blog-app/assets/119053190/f1519736-07fe-41f3-96f0-cc5d9f542491)
![Screenshot (90)](https://github.com/tajulafreen/Blog-app/assets/119053190/ce159607-6f36-4c89-ac55-7c89d4900f0b)
- After fixing the N+1 issue - In the Post index page
![Screenshot (91)](https://github.com/tajulafreen/Blog-app/assets/119053190/f6422d9f-11be-424e-8204-f170d8710f47)
- After fixing the N+1 issue - In the Post show page
![Screenshot (92)](https://github.com/tajulafreen/Blog-app/assets/119053190/35d933ee-0180-4ff0-b175-b2383e40f848)
- Used Capybara to write integration tests for each view in the project.
- User index page:
   - I can see the username of all other users.
   - I can see the profile picture for each user.
   - I can see the number of posts each user has written.
   - When I click on a user, I am redirected to that user's show page.
- User show page:
   - I can see the user's profile picture.
   - I can see the user's username.
   - I can see the number of posts the user has written.
   - I can see the user's bio.
   - I can see the user's first 3 posts.
   - I can see a button that lets me view all of a user's posts.
   - When I click a user's post, it redirects me to that post's show page.
   - When I click to see all posts, it redirects me to the user's post's index page.
- User post index page:

   - I can see the user's profile picture.
   - I can see the user's username.
   - I can see the number of posts the user has written.
   - I can see a post's title.
   - I can see some of the post's body.
   - I can see the first comments on a post.
   - I can see how many comments a post has.
   - I can see how many likes a post has.
   - I can see a section for pagination if there are more posts than fit on the view.
   - When I click on a post, it redirects me to that post's show page.

- Post show page:

  - I can see the post's title.
  - I can see who wrote the post.
  - I can see how many comments it has.
  - I can see how many likes it has.
  - I can see the post body.
  - I can see the username of each commenter.
  - I can see the comment each comment left.

2023-10-10 22:37 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @tajulafreen and @porag-m06 

### Nice job, you are almost there.

![cat-driving-serious](https://user-images.githubusercontent.com/68796232/223284600-852bcd90-1495-4a40-8515-cc12636b369b.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-10-10 22:37 UTC, Omar-Muhamad commented on spec/integration/users/user_show_spec.rb
> +  end
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/intergration_spec_and_n_1_project.md#:~:text=first%203%20posts.-,I%20can%20see%20a%20button%20that%20lets%20me%20view%20all%20of%20a%20user%27s%20posts.,-When%20I%20click), Please add a test that asserts you can see a button that lets me view all of a user's posts.

2023-10-10 22:37 UTC, omar-muhamad commented on spec/integration/posts/post_index_spec.rb
> +    end
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/intergration_spec_and_n_1_project.md#:~:text=a%20post%27s%20title.-,I%20can%20see%20some%20of%20the%20post%27s%20body.,-I%20can%20see), Please add a test that asserts you can see some of the post's body because you forgot to add it.

2023-10-10 22:37 UTC, omar-muhamad commented on spec/integration/posts/post_index_spec.rb
> +  end
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/intergration_spec_and_n_1_project.md#:~:text=a%20post%20has.-,I%20can%20see%20a%20section%20for%20pagination%20if%20there%20are%20more%20posts%20than%20fit%20on%20the%20view.,-When%20I%20click), Please add a test that asserts you can see a section for pagination if there are more posts than fit on the view.

2023-10-11 14:13 UTC, danmainah approved these changes
Hi @tajulafreen and @porag-m06 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ implemented the changes requested to add the missing test cases
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-11 14:17 UTC, merged