Blog-app : add devise for sign up user
tajulafreen/Blog-app pull request #9
Opened 2023-10-11 20:56 UTC by tajulafreen

**In this PR I did the following:**

- Removed current_user method in ApplicationController, devise will provide with one.
- [Install and setup devise](https://github.com/heartcombo/devise#getting-started).
- Can register a new user.
- User logs in with a combination of email and password.
- Hashed password is stored in the database.
- Asked for confirmation of email.
- Can reset password.

2023-10-12 10:32 UTC, algerina commented
Hi @tajulafreen , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project where Linters are not passing.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-10-12 10:41 UTC, Shedrack-Sunday requested changes
Hi @tajulafreen 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request 🔴 

You have submitted a project, that does not have your partner's commit. ensure that he has contributed equally to the project  before submitting another review

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-10-13 15:10 UTC, cynthiainga requested changes
Hi @tajulafreen, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights

- [ ] The `current_user` method in `ApplicationController` has been removed ✔️ 
- [ ] Devise has been installed ✔️ 
- [ ] The application allows for registering a new user ✔️ 
- [ ] A user can log in with a combination of email and password ✔️ 
- [ ] A user can reset the password in the application ✔️ 
- [ ] A hashed password is stored in the database ✔️ 

## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇🏾 👇🏾 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-13 15:10 UTC, cynthiainga commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
- [ ] As mentioned in the project requirement `:confirmable` should be enabled in the user mode, user should be asked for confirmation of email. Kindly add it 🙃 🙃

2023-10-13 15:10 UTC, cynthiainga commented on app/controllers/users_controller.rb
> +    # @user = current_user
- [ ] Please kindly delete the commented line of code to keep your code clean and look more professional 😁

2023-10-13 16:00 UTC, Munsa1 approved these changes
Hi @tajulafreen, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Made Requested Changes :heavy_check_mark: 
: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-13 16:42 UTC, merged